### ISSUE TITLE
Updated for 1.8.0

### ISSUE THREAD

**Issue by derekschrock** [jlehen/mutt-parent_child_match#1]
Can this patch be updated for 1.8.0?

**Comment by jlehen** [comment]
I can have a look at it, no promises though.

**Comment by jlehen** [comment]
OK, it was actually easier than I thought.  I've pushed an updated version.  Can you please give it a spin?  I'm pretty confident it will work but a bit of testing won't hurt.

**Comment by jlehen** [comment]
Hey Derek, have you got a chance to test it?

**Comment by derekschrock** [comment]
Yeah, sorry I forgot to update this PR.
